### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by Plondrein** [ng-matero/extensions#73]
Now that Angular 13 is released, it would be cool to upgrade :)

**Comment by wupaz** [comment]
I'm stuck with this error 
SassError: Can't find stylesheet to import.
  ╷
2 │ @use '~@angular/material/core/theming/theming';
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by nzbin** [comment]
I intend to upgrade Angular 13 in next month.

**Comment by nzbin** [comment]
> I'm stuck with this error SassError: Can't find stylesheet to import. ╷ 2 │ @use '~@angular/material/core/theming/theming'; │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Maybe it doesn't support Angular 13, I haven't try.

**Comment by smorandi** [comment]
no it does not, angular 13 let the tilde go. so for angular 13 it should just work without the ~ in front of the statement.

@use „@angular/material/core/theming/theming“ should work…

**Comment by nzbin** [comment]
@smorandi Ok, I will checkout and fix this issue.

**Comment by smorandi** [comment]
that‘ll be fantastic.

i think there will be two parts for angular 13. one which will involve more work since they get rid of the „view-engine“, while ngcc still is in place, they probably will remove it in a future version.
so that would probably require more rework on the lib.

however, to make the scss angular 13 compatible, it really **might** just need that one change described earlier.

**Comment by nzbin** [comment]
I will upgrade Angular 13 this month, maybe this week.

**Comment by nzbin** [comment]
`v13` has released.

**Comment by davidecampello** [comment]
Thanks for your amazing job!

**Comment by Plondrein** [comment]
Thanks!
